# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Home
    url: http://tns.thss.tsinghua.edu.cn/ziggo/
    weight: 10
  - name: TSNPerf
    url: tsnperf/
    weight: 20
  - name: Switch
    url: switch/
    weight: 30
  - name: Device
    url: device/
    weight: 40
  # - name: Publications
  #   url: /#publication
  #   weight: 45
  # - parent: Tutorial
  #   name: Device
  #   url: device/
  #   weight: 50
  # - parent: Tutorial
  #   name: Switch
  #   url: switch/
  #   weight: 20
  # - parent: Tutorial
  #   name: TSNPerf
  #   url: tsnperf/
  #   weight: 10

    # name: 
  # - name: Contact
  #   url: /#Contact
